package assets

// ChronolithsFloorLore holds atmospheric snippets per Chronoliths floor.
var ChronolithsFloorLore = [11][]string{
	{ // Floor 0 — Anchorpoint
		"The Chronolith hums overhead. Time here is reliable. Almost oppressively so.",
		"Anchorpoint. Where clocks agree and calendars behave. Outside the radius, all bets are off.",
		"You step into the temporal stable-point. The air tastes like certainty.",
	},
	{ // Floor 1 — Amber Antechamber
		"Amber light filters through crystallised moments. The air is thick with preserved seconds.",
		"Frozen instants hang in alcoves like museum displays. Some of them are still warm.",
		"The antechamber was an entryway once. For what, the records disagree.",
	},
	{ // Floor 2 — Frozen Barracks
		"Soldiers mid-stride, caught in temporal amber. Their boots never touch the ground.",
		"Bunks made for rest that hasn't happened yet. The pillows remember heads that haven't arrived.",
		"A duty roster lists names in a language that won't be spoken for another century.",
	},
	{ // Floor 3 — The Repeating Hall
		"The corridor ahead looks familiar. The corridor behind looks identical. This is not coincidence.",
		"Footprints in the dust match your boots. They lead both directions. The dust is undisturbed.",
		"A clock on the wall strikes twelve. Then twelve. Then twelve. It is very sure about the time.",
	},
	{ // Floor 4 — Temporal Breach
		"The air crackles with displaced seconds. Your shadow arrives before you do.",
		"Cracks in the walls show glimpses of three different eras. None of them are reassuring.",
		"A warning sign reads: TEMPORAL BREACH — STAY CLEAR. The sign is from two timelines. Both are serious.",
	},
	{ // Floor 5 — Clockwork Sanctuary
		"Gears turn in perfect synchrony with something you can't see. The mechanism predates the building.",
		"Every surface is calibrated. Every angle is deliberate. The architect had more time than anyone.",
		"A plaque reads: THIS SANCTUARY HAS OPERATED FOR 0 YEARS AND FOREVER.",
	},
	{ // Floor 6 — The Paradox Wing
		"Effect precedes cause here. You stub your toe on a stone that you haven't reached yet.",
		"Two versions of the same corridor exist simultaneously. Neither acknowledges the other.",
		"A researcher's note: 'I am writing this before I think of it. The penmanship shows.'",
	},
	{ // Floor 7 — Timeline Scar
		"The scar where timelines collided has not healed. Temporal scar tissue lines the walls.",
		"You hear marching from three directions. Two of them are centuries away.",
		"The war left marks in time itself. These corridors are the bruises.",
	},
	{ // Floor 8 — War Room Seven
		"Maps of campaigns that ended before they started cover every surface. The pins are confident.",
		"This was the nerve center of Timeline Seven's war effort. The effort continues. The war does not.",
		"A general's desk is still warm. The general retired 300 years ago. Retirement was not a complete success.",
	},
	{ // Floor 9 — The Convergence
		"Multiple timelines press together here. The pressure is both metaphysical and quite literal.",
		"You can see yourself in the adjacent timeline. You are doing roughly the same thing. Neither of you waves.",
		"The convergence point is where all paths lead. All paths also lead away. Direction is having a crisis.",
	},
	{ // Floor 10 — The Eternal Moment
		"One moment, stretched to infinity. The moment does not object. It has time.",
		"The Recursion waits at the center of a moment that has no edges. It has been waiting. It will be waiting.",
		"You enter the last room. Or the first room. The distinction has been dissolved by committee.",
	},
}

// ChronolithsWallWritings holds inscription texts per Chronoliths floor.
var ChronolithsWallWritings = [11][]string{
	{}, // floor 0 — Anchorpoint (city uses CityInscriptions)
	{ // Floor 1 — Amber Antechamber
		"TEMPORAL ADVISORY: Past this point, cause and effect are guidelines.",
		"EXPEDITION LOG: Team entered at 0800. Team exited at 0755. We have revised the schedule.",
		"AMBER WARNING: Do not touch preserved moments. They remember being touched. They do not enjoy it.",
		"Researcher's Note: Day 1 — the clocks work normally. This will not last. It never does. It always does.",
		"FACILITY NOTICE: The antechamber was constructed in 3 tenses simultaneously. Please use the present one.",
		"The amber preserves everything. Including the screams. Especially the screams. The screams are very well-preserved.",
		"INTAKE FORM: Name: [varies]. Date of Entry: [varies]. Number of Entries: [please stop asking].",
		"Graffiti in faded ink: 'KILROY WAS HERE. KILROY WILL BE HERE. KILROY IS HAVING A CONFUSING DAY.'",
		"SAFETY NOTICE: Temporal amber is not edible. It is not inedible. It is both. This is not a recommendation.",
		"The stalactites drip something that isn't water. It tastes like a Tuesday afternoon in spring.",
		"GEOLOGICAL SURVEY: These ruins predate the civilisation that built them. We have filed a complaint with chronology.",
	},
	{ // Floor 2 — Frozen Barracks
		"PERSONNEL NOTICE: Soldiers in Barracks C have been frozen for 300 years. Their deployment status remains 'active'.",
		"War Room log: Day 1. Day 1. Day 1. Day 1. [This entry repeats for 400 pages.]",
		"BARRACKS REGULATION: Reveille is at 0600. Reveille was at 0600. Reveille will be at 0600. The bugle agrees to disagree.",
		"The bunks are made to military specification. The specification was issued by a command structure that will exist in forty years.",
		"SUPPLY REQUEST: 200 temporal stabilisers. STATUS: Delivered. DELIVERY DATE: Three weeks before the request was filed.",
		"Mess hall menu: yesterday's breakfast, tomorrow's lunch, and a dinner from a timeline where food is different.",
		"DRILL REPORT: Squad 7 completed the exercise before it began. Commendation: pre-emptive competence.",
		"A soldier's letter home: 'Dear family — I will arrive before this letter. Please set an extra place. For both of me.'",
		"MAINTENANCE LOG: Barracks heating system runs on temporal friction. The friction between Tuesday and Wednesday is adequate.",
		"INSPECTION RESULT: All equipment in chronological order. Unfortunately, chronological order is under review.",
	},
	{ // Floor 3 — The Repeating Hall
		"If you remember being here before, you were. If you don't, you will.",
		"LOOP ADVISORY: This corridor repeats. The repetition repeats. The advisory repeats. We apologise for the advisory.",
		"Researcher's Log: I have written this entry 47 times. Each time, the handwriting is slightly more resigned.",
		"STRUCTURAL NOTICE: This hall was designed to be traversed once. It has been traversed an uncountable number of times. By the same person.",
		"The footprints ahead are yours. The footprints behind are also yours. The footprints to the left are someone else's. They are also yours.",
		"MAINTENANCE NOTE: Clock in sector 7 is running backward. This is correct. Forward was the error.",
		"A plaque reads: IN MEMORY OF THE FIRST TRAVERSAL. Below it: IN MEMORY OF THE LAST TRAVERSAL. Both plaques are identical. Both are original.",
		"NAVIGATION AID: To exit the Repeating Hall, stop repeating. NOTE: This advice has never worked. It continues to be issued.",
		"Researcher's Note: Day 1 — entered the Hall. Day 1 — still in the Hall. Day 1 — beginning to notice a pattern.",
		"ARCHITECTURAL REVIEW: The Hall repeats because the architect submitted the same blueprint twice. The architect submitted it once.",
		"PERSONNEL UPDATE: Three researchers entered the Repeating Hall. Three researchers exited. They were the same researcher.",
	},
	{ // Floor 4 — Temporal Breach
		"BREACH CONTAINMENT STATUS: Ongoing. Duration: instantaneous and eternal. Please select one for the report.",
		"HAZARD LEVEL 6: The breach displaces cause and effect. If you feel an injury before receiving it, this is normal. Seek treatment retroactively.",
		"Technician's Note: The paradox in Lab 3 has resolved itself. Specifically, both resolutions occurred simultaneously. We have chosen to ignore this.",
		"TEMPORAL DISPLACEMENT LOG: Objects displaced this quarter: 47 tools, 12 chairs, 3 researchers, 1 concept of 'up'. Recovery pending.",
		"RESEARCH FINDING: The breach is not a hole in time. It is time having a disagreement with itself. Both sides make valid points.",
		"WARNING: Sound behaves differently past the breach. Your voice arrives before you speak. Conversations become predictions.",
		"EQUIPMENT NOTE: All clocks within 10 meters of the breach run simultaneously forward and backward. Average timekeeping: zero.",
		"A note taped to the wall: 'I will write this note in three hours. If you're reading it now, I was right. If not, check back.'",
		"BREACH MEASUREMENT: Width — variable. Depth — undefined. Duration — yes. These are the official measurements.",
		"SAFETY ADVISORY: Do not look directly into the breach. The breach is looking directly into you. This exchange is not equitable.",
	},
	{ // Floor 5 — Clockwork Sanctuary
		"The 4.7-second loop in Valley B has been playing for centuries. The loop contains a bird taking flight. The bird is very tired.",
		"SANCTUARY OPERATIONS: The clockwork runs on faith. Not metaphorical faith. Measurable, quantifiable faith. We are running low.",
		"CHRONO-HAZARD LEVEL 4: Do not touch the amber. Do not think about the amber. The amber is thinking about you. It has time.",
		"SANCTUARY DESIGN SPEC: Every gear serves a purpose. Several purposes have not yet been assigned. The gears are patient.",
		"Clockmaker's Log: The sanctuary runs at 99.97% temporal accuracy. The 0.03% discrepancy contains a Tuesday that refuses to end.",
		"RITUAL NOTICE: The Clock Priest will conduct the hourly calibration at all hours simultaneously. Attendance is mandatory and has already occurred.",
		"A brass plate reads: THIS MECHANISM HAS BEEN RUNNING FOR [ERROR: DURATION EXCEEDS AVAILABLE TENSES].",
		"MAINTENANCE SCHEDULE: Lubricate gears every century. Last lubrication: next century. Schedule compliance: technically perfect.",
		"The sanctuary hums at exactly 440Hz. This is also the frequency of mild existential uncertainty.",
		"VISITOR NOTE: The sanctuary is open to all. 'All' includes versions of yourself from other timelines. Please do not start arguments.",
	},
	{ // Floor 6 — The Paradox Wing
		"Construct #4471 has filed a complaint about its deployment date. Its deployment date has not occurred.",
		"PARADOX WING GUIDELINES: If you encounter yourself, introduce yourself politely. Do not share spoilers.",
		"RESEARCH LOG: We attempted to resolve the paradox in Room 12. The resolution created two additional paradoxes. Net progress: negative one.",
		"NOTICE TO STAFF: The door on the left leads to yesterday. The door on the right leads to tomorrow. Both are the same door.",
		"A sign reads: PARADOX-FREE ZONE. The sign is itself a paradox. We do not discuss the sign.",
		"Researcher's Log: Day 5 — I met myself from Day 3. I gave myself advice. Day 3 me did not take it. I understand why. I didn't take it either.",
		"CONTAINMENT REPORT: The paradox in Section C has stabilised. It now only contradicts itself on weekdays.",
		"TO ALL CONSTRUCTS: Your warranty has expired. Your warranty has not yet been issued. Both of these are your problem.",
		"PHILOSOPHICAL INQUIRY FORM: 'If a tree falls in a forest before the forest exists, does it make a sound?' STATUS: Pending. FILED: Before the form existed.",
		"PARADOX WING STATUS: Currently exists. Intermittently does not exist. Average existential status: probable.",
		"A note in hurried handwriting: 'The paradox is not the problem. The paradox is the solution. The problem is that it's also the question.'",
	},
	{ // Floor 7 — Timeline Scar
		"CASUALTY REPORT, TIMELINE SEVEN: Deceased — [CLASSIFIED]. Survivors — [CLASSIFIED]. Difference — [LESS THAN YOU'D HOPE].",
		"Timeline Seven ended. Timeline Seven is ending. Timeline Seven will have ended. Tense is a matter of perspective.",
		"SCAR ASSESSMENT: The scar tissue between timelines is load-bearing. Do not attempt temporal cosmetic surgery.",
		"MILITARY DISPATCH: Deploy Construct Battalion to Grid 7-14. DEPLOYMENT STATUS: Completed. DEPLOYMENT DATE: [RETROACTIVE].",
		"The scar runs through this corridor. On one side: the war that ended. On the other: the war that didn't. The corridor floor is neutral.",
		"ARCHAEOLOGICAL NOTE: This ruin predates the civilisation that will build it. We have notified the appropriate authorities. The authorities have not been born.",
		"Construct Memorial: 'We served. We serve. We will serve. Service transcends tense.'",
		"TIMELINE INTEGRITY CHECK: Compromised. Repair estimate: undefined. Responsibility: distributed across timelines that disagree on the definition of 'responsibility'.",
		"A soldier's final entry: 'The war is over. The war is over. The war is' — the entry continues in a handwriting that is not the soldier's.",
		"SCAR MONITORING STATION: No change detected. Change detected. Both readings are from the same instrument at the same time.",
	},
	{ // Floor 8 — War Room Seven
		"The frozen moment in corridor B contains a soldier mid-salute. He has been saluting for 300 years. He is very good at it.",
		"GENERAL'S ORDER #4471: 'Win the war.' AMENDMENT #1: 'Define win.' AMENDMENT #2: 'Define war.' AMENDMENT #3: 'Define.'",
		"WAR ROOM PROTOCOL: All decisions are final. All decisions are also pending. Both statuses are accurate for different values of 'time'.",
		"STRATEGIC ASSESSMENT: We have won. We have lost. We are currently winning-losing. The hyphen is load-bearing.",
		"Construct retirement notice: effective immediately, retroactively, and pre-emptively. Please stop fighting.",
		"AFTER-ACTION REVIEW: The battle was fought, won, lost, and declared a draw simultaneously. Morale is complicated.",
		"COMMENDATION: For valor in the face of temporal uncertainty. Recipient: all Constructs. Date: all dates.",
		"WAR ROOM INVENTORY: Maps — 47. Maps depicting events that occurred — 12. Maps depicting events that will occur — 12. Maps depicting events that might occur — 23.",
		"A general's desk note: 'The enemy surrendered yesterday. The enemy attacks tomorrow. Today is the paperwork.'",
		"CEASE-FIRE AGREEMENT: Signed by both parties. Neither party has started fighting. Both parties have finished fighting. The agreement is technically premature.",
	},
	{ // Floor 9 — The Convergence
		"CONVERGENCE ALERT: Multiple timelines intersecting in this sector. Please maintain your timeline of origin. If unsure, select one.",
		"Personnel Note: Researcher Venn entered the Convergence on Tuesday. Researcher Venn exited on Monday. The calendar has been revised.",
		"CONVERGENCE READINGS: Energy level — stable. Stability — unstable. Please see the previous sentence.",
		"WARNING: Objects in this corridor may be closer than they appear. Or further. Or both. Distance is having a difficult day.",
		"TIMELINE IDENTIFICATION GUIDE: Your timeline has a colour. If you can see the colour, you are in the correct timeline. If you cannot, you are in a better one.",
		"The convergence node pulses. Each pulse contains an entire era. The eras are compressed but not uncomfortable.",
		"RESEARCH SUMMARY: At the convergence, all possibilities coexist. Most possibilities are unhelpful. A few are impossible. One is a sandwich.",
		"NAVIGATION WARNING: The corridors ahead exist in multiple timelines. Following one will take you to your destination. Following another will also take you to your destination. In the other timeline.",
		"Convergence Technician's Log: 'I have calibrated the instruments. The instruments were already calibrated. By me. Tomorrow. I am efficient.'",
		"OFFICIAL NOTICE: The convergence is a natural phenomenon. 'Natural' is used loosely. 'Phenomenon' is used accurately.",
	},
	{ // Floor 10 — The Eternal Moment
		"The Chronolith at coordinate 7,14 marks the moment the war ended. Or started. The monument committee is still debating.",
		"THE ETERNAL MOMENT: You are here. You have always been here. You will always be here. Please form an orderly queue.",
		"RECURSION LOG: Entry 1 — see Entry 1. Entry 2 — see Entry 1. Entry 3 — we are beginning to see a pattern.",
		"The Recursion has been waiting for you. The Recursion will be waiting for you. The Recursion is waiting for you. Tense is decorative at this depth.",
		"FINAL REPORT: The experiment was a success. The success was a failure. The failure was expected. The expectation was the experiment.",
		"A researcher's last note: 'I have been here before. I will be here again. I am here now. All three statements are the same statement.'",
		"THE MOMENT DOES NOT END. THE MOMENT DOES NOT BEGIN. THE MOMENT IS. THIS IS SUFFICIENT.",
		"WARNING: Beyond this point, linear time is a courtesy. The courtesy has been withdrawn.",
		"TEMPORAL ENDPOINT: All clocks agree. They agree on nothing. This is, paradoxically, consensus.",
		"The Eternal Moment contains everything that has happened, is happening, and will happen. It is surprisingly cramped.",
		"INSCRIPTION ON THE FINAL DOOR: 'You may leave at any time. Any time includes this time. This time includes all time. You may leave.'",
	},
}

// ChronolithsEnemyLore maps enemy name to a one-line lore description.
var ChronolithsEnemyLore = map[string]string{
	"Time Beetle":      "eats seconds. The gap in your memory is where it fed.",
	"Chrono Sentry":    "guards a post that hasn't been assigned yet. It is very punctual.",
	"Temporal Spark":   "a lightning bolt from a storm that won't happen for 40 years. Early arrival.",
	"War Fragment":     "a piece of a soldier from Timeline Seven. The rest of the soldier is still fighting.",
	"Rusted Warden":    "forgot what it guards. Keeps guarding. Rust is not decay — it is loyalty oxidising.",
	"Paradox Engine":   "runs on contradictions. Fuel efficiency: impossible.",
	"Timeline Soldier": "from a war that ended, or hasn't started, or both. Its orders are classified by a command structure that doesn't exist yet.",
	"The Recursion":    "the same moment, experienced an infinite number of times, compressed into a body. It has done this before. It will do this again. It is doing this now.",
}
